# Generated by Django 4.1 on 2022-10-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_equipodefutbol_estadiofutbol_jugadorfutbol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiguYa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('nacionalidad', models.CharField(max_length=40)),
                ('posicion', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
                ('reseña', models.TextField(max_length=240)),
                ('imagen', models.ImageField(null=True, upload_to='figuritas')),
            ],
        ),
    ]
