# Generated by Django 4.1 on 2022-10-20 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppCoder', '0005_avatares'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatares',
            old_name='imagen',
            new_name='avatar',
        ),
        migrations.AlterField(
            model_name='avatares',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
